// Auto-generated by build.js - DO NOT EDIT
const LOGO_CONFIG = {
  "logoBySection": {
    "sec-0": {
      "text": "unconventional",
      "emphasizedText": "minds"
    },
    "sec-1": {
      "text": "unconventional",
      "emphasizedText": "solutions"
    },
    "sec-2": {
      "text": "unconventional",
      "emphasizedText": "method"
    },
    "sec-3": {
      "text": "unconventional",
      "emphasizedText": "market"
    },
    "sec-4": {
      "text": "unconventional",
      "emphasizedText": "contacts"
    }
  }
};
